import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { Hero } from "../scenes/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <div className="h-[600px]" />
      <footer className="h-[300px]">Footer Code</footer>
    </>
  );
}
